// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   5

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    esdt_faucet_sc
    (
        setLimit
        claim
        getMaxTokensPerTransaction
    )
}

elrond_wasm_node::wasm_empty_callback! {}
